[0m09:50:35.005985 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085d3e00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1095efb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1095ef9d0>]}


============================== 09:50:35.010790 | bf4c3b5b-6e5d-4b9e-afa6-2520ae0fbf2d ==============================
[0m09:50:35.010790 [info ] [MainThread]: Running with dbt=1.10.11
[0m09:50:35.011284 [debug] [MainThread]: running dbt with arguments {'write_json': 'True', 'static_parser': 'True', 'quiet': 'False', 'indirect_selection': 'eager', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'warn_error': 'None', 'introspect': 'True', 'printer_width': '80', 'profiles_dir': '/Users/rosemarie/.dbt', 'use_colors': 'True', 'log_cache_events': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'log_format': 'default', 'debug': 'False', 'cache_selected_only': 'False', 'partial_parse': 'True', 'target_path': 'None', 'use_experimental_parser': 'False', 'send_anonymous_usage_stats': 'True', 'no_print': 'None', 'invocation_command': 'dbt init xref-tables', 'empty': 'None'}
[0m09:50:43.880780 [debug] [MainThread]: Starter project path: /Users/rosemarie/dbt-env/lib/python3.13/site-packages/dbt/include/starter_project
[0m09:50:43.891196 [info ] [MainThread]: 
Your new dbt project "xref_tables" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:50:43.891958 [info ] [MainThread]: Setting up your profile.
[0m09:52:06.912333 [info ] [MainThread]: Profile xref_tables written to /Users/rosemarie/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m09:52:06.919268 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 91.97449, "process_in_blocks": "0", "process_kernel_time": 0.6278, "process_mem_max_rss": "360759296", "process_out_blocks": "0", "process_user_time": 2.286207}
[0m09:52:06.920730 [debug] [MainThread]: Command `dbt init` succeeded at 09:52:06.920562 after 91.98 seconds
[0m09:52:06.921271 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11d5248a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11d510ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11d4d8d10>]}
[0m09:52:06.921970 [debug] [MainThread]: Flushing usage events
[0m09:52:07.167296 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:52:21.227800 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10cb33e00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10db5fb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10db5f9d0>]}


============================== 09:52:21.232101 | 817cefef-1376-47c1-a02b-8e345fd6d82a ==============================
[0m09:52:21.232101 [info ] [MainThread]: Running with dbt=1.10.11
[0m09:52:21.232579 [debug] [MainThread]: running dbt with arguments {'invocation_command': 'dbt debug', 'log_cache_events': 'False', 'version_check': 'True', 'warn_error': 'None', 'profiles_dir': '/Users/rosemarie/.dbt', 'debug': 'False', 'printer_width': '80', 'send_anonymous_usage_stats': 'True', 'introspect': 'True', 'log_format': 'default', 'empty': 'None', 'write_json': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'cache_selected_only': 'False', 'fail_fast': 'False', 'partial_parse': 'True', 'use_colors': 'True', 'quiet': 'False', 'static_parser': 'True', 'indirect_selection': 'eager', 'no_print': 'None', 'target_path': 'None', 'use_experimental_parser': 'False', 'log_path': 'logs'}
[0m09:52:21.245092 [info ] [MainThread]: dbt version: 1.10.11
[0m09:52:21.245444 [info ] [MainThread]: python version: 3.13.2
[0m09:52:21.245688 [info ] [MainThread]: python path: /Users/rosemarie/dbt-env/bin/python
[0m09:52:21.245970 [info ] [MainThread]: os info: macOS-26.0.1-arm64-arm-64bit-Mach-O
[0m09:52:23.183011 [info ] [MainThread]: Using profiles dir at /Users/rosemarie/.dbt
[0m09:52:23.183405 [info ] [MainThread]: Using profiles.yml file at /Users/rosemarie/.dbt/profiles.yml
[0m09:52:23.183608 [info ] [MainThread]: Using dbt_project.yml file at /Users/rosemarie/Desktop/gcf-xref/dbt_project.yml
[0m09:52:23.183836 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m09:52:23.187184 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 2.0167043, "process_in_blocks": "0", "process_kernel_time": 0.481294, "process_mem_max_rss": "363380736", "process_out_blocks": "0", "process_user_time": 2.352476}
[0m09:52:23.187656 [debug] [MainThread]: Command `dbt debug` failed at 09:52:23.187589 after 2.02 seconds
[0m09:52:23.187901 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x121a2ad70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x121a84ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1219e5040>]}
[0m09:52:23.188168 [debug] [MainThread]: Flushing usage events
[0m09:52:23.408480 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:58:34.918307 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085a3e00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10978fb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10978f9d0>]}


============================== 09:58:34.922765 | 2f7e1ce3-128b-44d6-9be1-c15008ff3b94 ==============================
[0m09:58:34.922765 [info ] [MainThread]: Running with dbt=1.10.11
[0m09:58:34.923249 [debug] [MainThread]: running dbt with arguments {'debug': 'False', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'version_check': 'True', 'use_experimental_parser': 'False', 'fail_fast': 'False', 'invocation_command': 'dbt debug', 'log_format': 'default', 'write_json': 'True', 'log_cache_events': 'False', 'no_print': 'None', 'log_path': 'logs', 'send_anonymous_usage_stats': 'True', 'partial_parse': 'True', 'warn_error': 'None', 'introspect': 'True', 'target_path': 'None', 'indirect_selection': 'eager', 'static_parser': 'True', 'cache_selected_only': 'False', 'empty': 'None', 'profiles_dir': '/Users/rosemarie/.dbt', 'use_colors': 'True', 'printer_width': '80'}
[0m09:58:34.936821 [info ] [MainThread]: dbt version: 1.10.11
[0m09:58:34.937301 [info ] [MainThread]: python version: 3.13.2
[0m09:58:34.937550 [info ] [MainThread]: python path: /Users/rosemarie/dbt-env/bin/python
[0m09:58:34.937739 [info ] [MainThread]: os info: macOS-26.0.1-arm64-arm-64bit-Mach-O
[0m09:58:37.031093 [info ] [MainThread]: Using profiles dir at /Users/rosemarie/.dbt
[0m09:58:37.031596 [info ] [MainThread]: Using profiles.yml file at /Users/rosemarie/.dbt/profiles.yml
[0m09:58:37.031816 [info ] [MainThread]: Using dbt_project.yml file at /Users/rosemarie/Desktop/gcf-xref/dbt_project.yml
[0m09:58:37.032069 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m09:58:37.036222 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 2.1739655, "process_in_blocks": "0", "process_kernel_time": 0.548795, "process_mem_max_rss": "363347968", "process_out_blocks": "0", "process_user_time": 2.304985}
[0m09:58:37.036835 [debug] [MainThread]: Command `dbt debug` failed at 09:58:37.036756 after 2.17 seconds
[0m09:58:37.037127 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11d4aad70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11d504ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11d465040>]}
[0m09:58:37.037412 [debug] [MainThread]: Flushing usage events
[0m09:58:37.279258 [debug] [MainThread]: An error was encountered while trying to flush usage events
